on: [push, workflow_dispatch]
name: Linux_Container_Workflow

env:
  AWS_REGION: ap-northeast-2                   
  # ECR_REPOSITORY: aws-webapp
  IMAGE_PATH: Dockerfile
  ECR_REGISTRY: 022499044118.dkr.ecr.ap-northeast-2.amazonaws.com
  # IMAGE_TAG: ${{ github.sha }}
  IMAGE_NAME: 022499044118.dkr.ecr.ap-northeast-2.amazonaws.com/aws-webapp:${{ github.sha }}
  API_URL: https://api-japac-ccr.xdr.jp.paloaltonetworks.com/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64
  API_KEY_ID: 34
  API_KEY: H5rmQ8E7xQl0uN5kcBbPGgdlPsXB5nqljBe9VBrqFVICoIHOO3bqymszBliK8cfvxX1gIUCtRGLQ3jNLPFBlvsRW65ZGPQpxBhNpSx5imawo9IXtenMOGyq9Gv9uQZIe
jobs:
    build-and-scan-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Download CortexCLI from the CC Console # using CC Scan
          run: |
            
       
            curl -s -o cortexcli $(curl -s "https://api-japac-ccr.xdr.jp.paloaltonetworks.com/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64" -H "x-xdr-auth-id: ${{env.API_KEY_ID}}" -H "Authorization: ${{env.API_KEY}}" | jq -r ".signed_url") 
            chmod +x cortexcli
# curl -v "https://api-japac-ccr.xdr.jp.paloaltonetworks.com/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64" \ -H "x-xdr-auth-id: 15" \ -H "Authorization: ${{env.API_KEY}}" \ | jq -r ".signed_url"
#curl -s -o cortexcli.pkg $(curl -s "https://api-japac-ccr.xdr.jp.paloaltonetworks.com/public_api/v1/unified-cli/releases/download-link?os=darwin&architecture=amd64" -H "x-xdr-auth-id: ${{env.API_KEY_ID}}" -H "Authorization: ${{env.API_KEY}}" | jq -r ".signed_url") 
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build and Scan the image
          # env:
          #   ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          #   IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -t $IMAGE_NAME .
            docker save $IMAGE_NAME > dockerimage.tar

            ./cortexcli \
            --api-base-url ${{ env.API_URL }} \
            --api-key ${{ env.API_KEY }} \
            --api-key-id ${{ env.API_KEY_ID }} \
            image scan dockerimage.tar
        - name: Push the image to Amazon ECR
          id: build-image
          run: |
            docker push $IMAGE_NAME

